### ISSUE TITLE
Error while trying to broadcast a sample to IOTA

### ISSUE THREAD

**Issue by ntsiam** [ptzianos/hermes#6] opened 2019-05-15 13:58 UTC
I get the following error now, whenever the app tries to broadcast data:
```
2019-05-15 15:56:15.271 32073-32338/org.hermes I/IOTAConnector: c2e0dd0f-3a8e-4b7d-93be-68be52f1303e -- Broadcasting 19 transactions to address: RUVVWZESHRMZKKYPUQD9HLYETIPZSLE9KJBSFMLVHSYZMWLQEOWT9XZGEDJJNGSCKRMDMJZIPWWXXNHIWLMXTRYEOC (1/3 tries)
2019-05-15 15:56:16.811 32073-32338/org.hermes E/IOTAConnector: c2e0dd0f-3a8e-4b7d-93be-68be52f1303e -- There was an error while trying to broadcast a sample to IOTA: java.lang.IllegalAccessError: 429 
```

**Comment by ptzianos** [comment] 2019-05-15 15:14
This is a duplicate of https://github.com/ptzianos/hermes/issues/2. The difference is that now the code catches the exception and prints it out instead of crashing. It's the result of the IOTA servers being overloaded and responding with a 429 to rate limit requests.

**Closed by ptzianos** 2019-05-15 15:14 UTC
